# Generated by Django 4.1.5 on 2023-02-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='docimage/')),
                ('catagory', models.CharField(choices=[('bone', 'bone'), ('lungs', 'lungs'), ('kindey', 'kindey'), ('ear', 'ear'), ('eye', 'eye')], max_length=50)),
            ],
        ),
    ]
