# Generated by Django 4.1.5 on 2023-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='catagory',
            field=models.CharField(choices=[('bone', 'bone'), ('lungs', 'lungs'), ('kindey', 'kindey'), ('ear', 'ear'), ('eye', 'eye')], max_length=50),
        ),
    ]
